default: &default
  adapter: mysql2
  host: 127.0.0.1
  pool: 5
  username: root
  password:
  encoding: utf8

development:
  <<: *default
  database: quiz

test:
  <<: *default
  database: test_quiz

production:
  <<: *default
  database: quiz